# Generated by Django 5.1.7 on 2025-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0007_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('filling', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=0, max_digits=10)),
                ('event_date', models.DateField()),
                ('social_media', models.CharField(choices=[('ВКонтакте', 'ВКонтакте'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Email', 'Email')], max_length=20)),
                ('vk_link', models.URLField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка по городу', 'Доставка по городу')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
