# Generated by Django 5.1.7 on 2025-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0008_customcakeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
