# Generated by Django 5.1.7 on 2025-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0009_alter_customcakeorder_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='social_media',
            field=models.CharField(choices=[('ВКонтакте', 'ВКонтакте'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram')], max_length=20),
        ),
    ]
