# Generated by Django 5.1.7 on 2025-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0010_alter_customcakeorder_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='social_media',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram')], max_length=20),
        ),
    ]
