# Generated by Django 5.1.7 on 2025-03-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0012_remove_customcakeorder_vk_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCakeOrder',
        ),
    ]
