# Generated by Django 5.1.7 on 2025-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0013_delete_customcakeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('filling', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('event_date', models.DateField()),
                ('social_media', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка по городу', 'Доставка по городу')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
