# Generated by Django 5.1.7 on 2025-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0017_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество на складе (шт.)'),
        ),
    ]
