# Generated by Django 5.1.7 on 2025-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0019_update_dessert_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card_on_delivery', 'Картой при получении')], default='card_on_delivery', max_length=50),
        ),
    ]
