# Generated by Django 5.1.7 on 2025-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0020_order_comment_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('ready', 'Готов к выдаче'), ('received', 'Получен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
