# Generated by Django 5.1.7 on 2025-04-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
    ]
