# Generated by Django 5.1.7 on 2025-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0028_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_slug',
            field=models.SlugField(blank=True, max_length=110, null=True),
        ),
    ]
