# Generated by Django 5.1.7 on 2025-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0029_product_type_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(max_length=150, verbose_name='Должность')),
                ('experience', models.TextField(verbose_name='Опыт')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('message', models.TextField(verbose_name='Сообщение от сотрудника')),
                ('about_work', models.TextField(verbose_name='О работе в Whisk & Wonder')),
                ('favorite_dessert', models.CharField(max_length=255, verbose_name='Любимый десерт')),
                ('favorite_drink', models.CharField(max_length=255, verbose_name='Любимый напиток')),
                ('image_path', models.CharField(help_text='Пример: img/barista.jpg', max_length=255, verbose_name='Путь к изображению (static)')),
            ],
        ),
    ]
