# Generated by Django 5.1.7 on 2025-05-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confectionary', '0031_event_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date(2024, 1, 1), help_text='Укажите дату проведения мероприятия', verbose_name='Дата мероприятия'),
            preserve_default=False,
        ),
    ]
